name: read from hello.txt

on:
  push:
    branches:
      - main

jobs:
  read:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: read and log from hello.txt
        run: |
          echo "Contents of hello.txt:"
          cat hello.txt

